### ISSUE TITLE
Can't resolve nucleo.css

### ISSUE THREAD

**Issue by akirataguchi115** [barunespadhy/Rangolio#1]
![image](https://github.com/barunespadhy/Rangolio/assets/31825085/48989147-c8ac-4d0b-bd3e-bcf1ee098439)
![image](https://github.com/barunespadhy/Rangolio/assets/31825085/d054c2d9-7347-4ba8-a444-0b7e0a1b3aaa)

**Comment by barunespadhy** [comment]
This project currently uses [argon-design-system-react](https://github.com/creativetimofficial/argon-design-system-react) for the design. argon-design-system-react has been added to this project as a submodule, and running npm install from the source of that submodule to fix that project's deps should fix it. So basically:

`
cd src/assets/argon-design-system-react/
npm install -i
`

**Comment by barunespadhy** [comment]
This is actually not needed anymore, as of [3e9220e545f47b2ce32ce9d23c762b0dd30e4495](https://github.com/barunespadhy/Rangolio/commit/3e9220e545f47b2ce32ce9d23c762b0dd30e4495), the gitsubmodule was removed and merged with the main project
